name: Laravel Zero
on:
  schedule:
    - cron: "25 */6 * * *"
  #push:
  #  paths-ignore: ['data/**']
  #  branches: [main]
  workflow_dispatch:
    inputs:
      temp:
        description: 'Temporär'
        required: false
permissions:
  contents: write
jobs:
  laravel-zero-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    
    - name: Copy .env
      working-directory: ./bin
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      working-directory: ./bin
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Execute Laravel Zero Datenblatt executable
      working-directory: ./bin
      run: php datenblatt fetch:iptv
    
    - name: Commit files
      run: |
        git config --local user.email "datenblatt+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -a -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
