name: ActionTest

on:
  workflow_dispatch: # Allow manual triggers
  push:
    tags-ignore:
      - '**' # Ignore any tags here
    branches:
      - main
    #
    # Trigger when either files in the docs folder,
    # the requirements.txt file or the mkdocs.yml file
    # are edited and commited.
    paths:
      - 'data/**'
      - 'requirements.txt'
      - 'mkdocs.yml'

# These permissions are required for it to work
permissions:
  contents: read
  pages: write
  id-token: write

# Makes sure only one workflow runs at a time.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    # This environment is required!
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url }}
    steps:
      - name: Send notification to webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"repository": "joelwmale/webhook-action"}'
          body: '{"event": "deployment", "repository": "joelwmale/webhook-action", "message": "Datenblatt has been deployed"}'
          github_event_payload: true    
